#!/usr/bin/python3

"""
Xcent - extract and classify named entities
"""

import re
import subprocess
import sys
from getopt import getopt
import fileinput

fimfrase = r"[.?!:]\s*"
mark_s = "#s_"
mark_e = ("{","}")

def markS(text):    
    fimfrase = r"([.?!:]+\s*)"
    text = re.sub(fimfrase, r"\1"+ mark_s, text)
    text = re.sub(r"([A-Z][a-z]?\. )" + mark_s + r"([A-Z])", r"\1\2" , text)
    return text

def markE(text):
    d = r"(?:da|do|de|dos|das)"
    #pM = r"[A-ZÂ]\w+"
    pM = r"(?:[A-ZÂ]\w+|[A-Z]\.|[A-Z][a-z]\.)"
    #nP = pM + " " + "(" + pM + " " + "|" + d + " " + pM + ")*" #feioso, problemas com espaços
    nP = f"{pM}(?: {pM}| {d} {pM})*"
    text = re.sub(r"\b" + f"({nP})", mark_e[0] + r"\1" + mark_e[1], text)
    return text

def listE(text):
    return re.findall(r"\{(.*?)\}",text)

def printE(entities):
    for ent in entities:
        print(ent)

def gabE(entities):
    #d = {}
    #for i in entities:
        #d[i]=f.get(i,0)+1
        #if not i in d:
        #    d[i]=0
        #d[i]+=1
    #return d
    return Counter(entities)

def printBagE(b):
    l=b.items()
    sorted(l.items(),key=lambda p: p[1], reverse=True)
    for i in l:
        a,b = i
        print(b,a)

def markD(txt):
    meses="janeiro fevereiro março abril maio".split()
    estacoes="primavera verão outono inverno".split()
    dias=[x+"-feira" for x in "segunda terça quarta quinta sexta".split()].extend("sábado domingo")
    text=re.sub("("+"|".join(meses+estacoes+dias)
    text=re.sub(r'(\b\d{4}\b)',r'{\1:t}',text)
    retjurn text
def main():
    opts, resto = getopt(sys.argv[1:], "alb")
    dop = dict(opts)

    texto = ""

    # Reads file
    for line in fileinput.input(resto):
        texto += line

    if "-a" in dop:
        print(markE(markS(texto)))
    elif "-l" in dop:
        printE(listE(markE(markS(texto))))
    elif "-b" in dop:
        print(bagE(listE(markE(markS(texto)))))
    elif "-d" in dop:
        #print("Não implementado!")
        printE(listE(markD(markS(texto))))
#elif "-b" in dop:
    #terminar Output:
    # 500 Carlos
    # 300 Ramalhete
# 10 Afonso