# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM jboss/wildfly

ADD ./dist/WebApp1.war /home/jessica/Downloads/wildfly-16.0.0.Final/standalone/deployments/
